### ISSUE TITLE
Tangle methods did not work

### ISSUE THREAD

**Issue by ghost** [rougier/dotemacs#1]
C-c C-v s ask evalute (my/org-sidebar) on your system yes or no, yes ---> can not open load file or directory imenu-list

C-c C-v t, gave me init.el and early-init.el I copied in .emacs.d/
it built the modules and at the end it had this message Symbol definition is void : org-make-tags-matcher
https://ibb.co/DK9zznr

**Comment by rougier** [comment]
I pusged some changes but probably I forgot to load org before using the `org-make-tags-matcher`. Note that before being to use the config-mode, you'll need to tangle the configuration at last once.

**Comment by rougier** [comment]
Another solution (maybe) would be to evaluate `Personal library / Configuration / Bugfix` and then tangle the file.

**Comment by rougier** [comment]
Is it working now?

**Comment by ghost** [comment]
This method worked, evaluate Personal library / Configuration / Bugfix and then tangle the file.
